// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(EMSContext))]
    partial class EMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.ConferenceRoom", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomID");

                    b.HasIndex("HotelID");

                    b.ToTable("ConferenceRooms");
                });

            modelBuilder.Entity("EMS.API.Models.Hotel", b =>
                {
                    b.Property<int>("HotelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelID");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("EMS.API.Models.Investor", b =>
                {
                    b.Property<int>("InvestorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestorID"));

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestorID");

                    b.ToTable("Investors");
                });

            modelBuilder.Entity("EMS.API.Models.InvestorSector", b =>
                {
                    b.Property<int>("InvestorSectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestorSectorID"));

                    b.Property<int>("InvestorID")
                        .HasColumnType("int");

                    b.Property<int>("SectorID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TimeTo")
                        .HasColumnType("time");

                    b.HasKey("InvestorSectorID");

                    b.HasIndex("InvestorID");

                    b.HasIndex("SectorID");

                    b.ToTable("InvestorSectors");
                });

            modelBuilder.Entity("EMS.API.Models.Presenter", b =>
                {
                    b.Property<int>("PresenterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PresenterID"));

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PresenterID");

                    b.ToTable("Presenters");
                });

            modelBuilder.Entity("EMS.API.Models.PresenterSector", b =>
                {
                    b.Property<int>("PresenterSectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PresenterSectorID"));

                    b.Property<int>("PresenterID")
                        .HasColumnType("int");

                    b.Property<int>("SectorID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TimeTo")
                        .HasColumnType("time");

                    b.HasKey("PresenterSectorID");

                    b.HasIndex("PresenterID");

                    b.HasIndex("SectorID");

                    b.ToTable("PresenterSectors");
                });

            modelBuilder.Entity("EMS.API.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<int>("InvestorID")
                        .HasColumnType("int");

                    b.Property<int>("PresenterID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SectorID")
                        .HasColumnType("int");

                    b.Property<int>("SlotID")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("InvestorID");

                    b.HasIndex("PresenterID");

                    b.HasIndex("SectorID");

                    b.HasIndex("SlotID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("EMS.API.Models.RoomTimeSlot", b =>
                {
                    b.Property<int>("SlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotID"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TimeTo")
                        .HasColumnType("time");

                    b.HasKey("SlotID");

                    b.HasIndex("RoomID");

                    b.ToTable("RoomTimeSlots");
                });

            modelBuilder.Entity("EMS.API.Models.Sector", b =>
                {
                    b.Property<int>("SectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectorID"));

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectorID");

                    b.ToTable("Sectors");

                    b.HasData(
                        new
                        {
                            SectorID = 1,
                            SectorName = "Finance"
                        },
                        new
                        {
                            SectorID = 2,
                            SectorName = "IT"
                        },
                        new
                        {
                            SectorID = 3,
                            SectorName = "Restaurants"
                        },
                        new
                        {
                            SectorID = 4,
                            SectorName = "Real Estate"
                        },
                        new
                        {
                            SectorID = 5,
                            SectorName = "Retail"
                        },
                        new
                        {
                            SectorID = 6,
                            SectorName = "Healthcare"
                        },
                        new
                        {
                            SectorID = 7,
                            SectorName = "Education"
                        },
                        new
                        {
                            SectorID = 8,
                            SectorName = "Manufacturing"
                        },
                        new
                        {
                            SectorID = 9,
                            SectorName = "Tourism"
                        },
                        new
                        {
                            SectorID = 10,
                            SectorName = "Media"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.ConferenceRoom", b =>
                {
                    b.HasOne("EMS.API.Models.Hotel", "Hotel")
                        .WithMany("ConferenceRooms")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("EMS.API.Models.InvestorSector", b =>
                {
                    b.HasOne("EMS.API.Models.Investor", "Investor")
                        .WithMany("InvestorSectors")
                        .HasForeignKey("InvestorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.API.Models.Sector", "Sector")
                        .WithMany("InvestorSectors")
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("EMS.API.Models.PresenterSector", b =>
                {
                    b.HasOne("EMS.API.Models.Presenter", "Presenter")
                        .WithMany("PresenterSectors")
                        .HasForeignKey("PresenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.API.Models.Sector", "Sector")
                        .WithMany("PresenterSectors")
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presenter");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("EMS.API.Models.Reservation", b =>
                {
                    b.HasOne("EMS.API.Models.Investor", "Investor")
                        .WithMany("Reservations")
                        .HasForeignKey("InvestorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.API.Models.Presenter", "Presenter")
                        .WithMany("Reservations")
                        .HasForeignKey("PresenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.API.Models.Sector", "Sector")
                        .WithMany("Reservations")
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.API.Models.RoomTimeSlot", "RoomTimeSlot")
                        .WithMany("Reservations")
                        .HasForeignKey("SlotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");

                    b.Navigation("Presenter");

                    b.Navigation("RoomTimeSlot");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("EMS.API.Models.RoomTimeSlot", b =>
                {
                    b.HasOne("EMS.API.Models.ConferenceRoom", "ConferenceRoom")
                        .WithMany("RoomTimeSlots")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceRoom");
                });

            modelBuilder.Entity("EMS.API.Models.ConferenceRoom", b =>
                {
                    b.Navigation("RoomTimeSlots");
                });

            modelBuilder.Entity("EMS.API.Models.Hotel", b =>
                {
                    b.Navigation("ConferenceRooms");
                });

            modelBuilder.Entity("EMS.API.Models.Investor", b =>
                {
                    b.Navigation("InvestorSectors");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EMS.API.Models.Presenter", b =>
                {
                    b.Navigation("PresenterSectors");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EMS.API.Models.RoomTimeSlot", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EMS.API.Models.Sector", b =>
                {
                    b.Navigation("InvestorSectors");

                    b.Navigation("PresenterSectors");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
